# Generated by Django 4.2.16 on 2024-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MandrillEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField()),
            ],
        ),
    ]
